apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-service
  template:
    metadata:
      labels:
        app: config-server-service
    spec:
      containers:
      - name: config-server-service
        image: meet1699/config-server-service:latest
        ports:
        - containerPort: 8088